# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c0fc6194b7cf514a47b4b483652f9070711830e67992f3e9888a2a91565f3f2163022fbd420f8ec8b89bf79cbd4f1179c5a7390a940c7ad82b3a186eabe02f

test:
  secret_key_base: b945d15bca85a63921ae855ef2bae25942b05b6f012bbc5dfd63031e3b3cf906ea795a45b0e3532fb4acbaefa9cde510ba72e1a81fb9f3a6c357dedec95e253b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
